### ISSUE TITLE
Invisible votes

### ISSUE THREAD

**Issue by erzett** [drbig/cddaiv#1]
![image](https://cloud.githubusercontent.com/assets/9295116/6271865/090ccfa4-b864-11e4-8e5f-d46738cffd6d.png)

I'm no mathematician, but 4 - 0 = 5 seems wrong to me.
I'm not sure if someones vote isn't being displayed or if a vote is counted twice, but there seems to be a bug somewhere. Is this perhaps due to a non-verified users' vote? If so, the vote summary should reflect that somehow

This is on Windows 7 64 bit, Chrome. I'm getting the same on IE, also being logged out doesn't change anything.

**Comment by drbig** [comment]
Thanks for reporting. I think I know what's broken here: the code that removes non-verified users probably doesn't recalculate the score. In the meantime I've checked and fixed the score. And yeah the 'math' is there to see if everything adds up properly and to judge whether something is 'controversial'.

**Comment by drbig** [comment]
I'll update the server software in a minute; I'll need to fix the miscalculated issues first.

**Comment by drbig** [comment]
All done.
