### ISSUE TITLE
Search issues

### ISSUE THREAD

**Issue by remyroy** [drbig/cddaiv#3]
It would be nice to be able to search issues. Maybe there is some Github API that could be reused for that?

**Comment by Mattamue** [comment]
:D

**Comment by drbig** [comment]
But GitHub is one click away from cddaiv ;)

Also to be perfectly honest cddaiv is rather hand-rolled in terms of the whole app structure. Would do it differently now (see e.g. [cartographer](https://github.com/drbig/cartographer)). Given that I'm not very much for adding more features to cddaiv as it is.

Also CopperTube on IRC can search github issues :)

**Comment by remyroy** [comment]
I was relaying [this comment](https://www.reddit.com/r/cataclysmdda/comments/3wtcfp/cast_your_vote_on_what_features_or_bugs_should_be/cy02egr) from reddit. He was looking to vote on something but he could not find it.
